### ISSUE TITLE
paper: counts versus flux

### ISSUE THREAD

**Issue by dhuppenkothen** [dhuppenkothen/ShiftyLines#4]
Add part to paper about using counts rather than fluxes for comparing model to data.

**Comment by vicgrinberg** [comment]
Also add why it is important and good that we work on unbinned data.

**Comment by dhuppenkothen** [comment]
In this context, we need to be careful with the word "unbinned". In general, this describes data that consists of *events*, which is not what we have. X-ray spectroscopy people consider a data set "unbinned" if it is in the native resolution of the instrument, even if that instrument produces binned data in the statistical sense (because photons are sorted into discrete channels, and we have counts per channel).

**Comment by dhuppenkothen** [comment]
Done
